                <h2>Hola Amigos!</h2>
                <p>Este es un espacio de "Guías Útiles" Para facilitarte el juego! Esperamos que te guste!</p>
				<br/>

<h2>Team Speak 3</h2>
<br>
<p>
    Para instalar TeamSpeak y poder comunicarte con nosotros solo tenes que hacer click <a href="http://www.teamspeak.com/?page=downloads">aca</a> y elegir la opcion de descarga que le corresponda a tu computadora.
    
</p>

<br>
<h2>COMANDOS PARA PROTECCIONES</h2>
<br>
<p><b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Como creo mi protecci&oacute;n?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Primero debemos conseguir una palo de madera .Una vez conseguido, hacer click izquierdo en una esquina de tu casa y luego con el click derecho en la esquina contraria que abarque todo lo que quieras proteger. Tienes que marcar esos dos puntos en un cubo imaginario como se ve en el ejemplo:</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
&nbsp;</p>

<div class="separator" style="margin: 0px; outline: none; padding: 0px; color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; clear: both; text-align: center;"><a href="http://minecraft.fr/wp-content/uploads/2011/09/Cuboid.png" imageanchor="1" style="color: rgb(0, 158, 184); outline: none; text-decoration: none; -webkit-transition: color 0.3s; transition: color 0.3s; display: inline; margin-right: 1em; margin-left: 1em; margin-top: 0px !important; margin-bottom: 0px !important;"><img border="0" height="119" src="http://minecraft.fr/wp-content/uploads/2011/09/Cuboid.png" style="border-width: 9px; border-image-source: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAAOVBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///+8yHYvAAAAEnRSTlMAAgEDBAUJBwYzCw0UChARDghnBteEAAAAhElEQVR4XnWRSxJDIQgEEx1Axd/L/Q8bKCuuyOzsohHxdZLS25LSOV2ULQdflgEiIDu9KqiIFILXXpeEx2ChXwdnKNxUGxc4dZbNfXjPufkp5H0Nwtymq/dltUIweNy9qmXt08EgydDZ6+dT+9Qh9AeGenhROFI0fPjMaCHx6uIlh9/xBSJuB3l0A/6JAAAAAElFTkSuQmCC); border-image-slice: 9; border-image-width: 9px; border-image-repeat: stretch; position: relative; box-sizing: border-box; display: inline-block; height: auto; margin: 10px auto; max-width: 100%; padding: 8px; -webkit-border-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAAOVBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///+8yHYvAAAAEnRSTlMAAgEDBAUJBwYzCw0UChARDghnBteEAAAAhElEQVR4XnWRSxJDIQgEEx1Axd/L/Q8bKCuuyOzsohHxdZLS25LSOV2ULQdflgEiIDu9KqiIFILXXpeEx2ChXwdnKNxUGxc4dZbNfXjPufkp5H0Nwtymq/dltUIweNy9qmXt08EgydDZ6+dT+9Qh9AeGenhROFI0fPjMaCHx6uIlh9/xBSJuB3l0A/6JAAAAAElFTkSuQmCC) 9 fill / 9px stretch;" width="320" /></a></div>

<p><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Luego si deseas puedes escribir&nbsp;/res select cost para saber cuanto te costara.</span></p>

<p><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Para crear la protecci&oacute;n, escribe: /res create NOMBRE y tu casa ya estar&aacute; protegida!!.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Cuantas protecciones puedo realizar?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">El limite de cada jugador es de 4 residencias</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Que son subzonas y como se hacen?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Las subzonas son como un residence dentro de otro, te permite cambiar los permisos que solo tendr&aacute;n efecto en esa subzone.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Se hace marcando la zona como un residence normal, entonces, estando dentro del residence, escribes /res subzone NOMBRESUBZONE y tu subzona estar&aacute; creada.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Que es eso de a&ntilde;adidos y como se hacen?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Los a&ntilde;adidos son expansiones de terreno al que quieras ampliar tu protecci&oacute;n, sin tener que borrar y crear de nuevo el /res</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Para hacerlo, selecciona el &aacute;rea a a&ntilde;adir, como si se fuera a crear un nuevo res. Si hay que usar el /res select expand, se usa. Cuando tengamos seleccionado el nuevo &aacute;rea, el comando a usar es el siguiente:</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res area [add/remove/replace] &lt;residence&gt; [areaID] - Donde residence es la residencia principal, y donde areaID es el &aacute;rea a a&ntilde;adir.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Ejemplo: si quisi&eacute;ramos a&ntilde;adir &aacute;rea en la zona norte de Ciudad:</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res area add Ciudad zonanorte</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Con /res area list residence, vemos la lista de las &aacute;reas a&ntilde;adidas en una residencia.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Como extra, si ponemos /res info, nos saldr&aacute; en: Current Area: main. Esto quiere decir que es el &aacute;rea del res principal</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Si lo hacemos en la zona a&ntilde;adida, en current area nos saldr&aacute; el nombre que le hayamos puesto.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Como se configura los permisos del residence y que configuraciones hay?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Te colocas dentro de la res&nbsp;y escribes lo siguiente:</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set build false o true - Desactiva o activa el que la gente pueda construir en tu residence.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set container false o true - Desactiva o activa el que la gente puede usar ba&uacute;les en tu residence.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set use false o true - Desactiva o activa el que la gente pueda usar botones, palancas, puertas,etc en tu residence.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set waterflow false o true - Desactiva o activa que solo el agua fluya en tu residence.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set move false o true - Desactiva o activa el que la gente pueda moverse en tu residence.</span></p>

<p><span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set destroy false o true - Desactiva o activa el que la gente pueda romper en tu residence.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set monsters false o true - Desactiva o activa que aparezcan monsters en tu residence (ojo, aparecer solo, se pueden meter si te siguen por ejemplo)</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set animals false o true - Desactiva o activa que aparezcan animales en tu residence</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res set pvp false o true - Desactiva o activa el pvp en tu residence. (solo funciona en mundos con pvp activado)</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Como borro una res?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Usa el comando /res remove NOMBRE y te saldr&aacute; un mensaje para confirmar el borrado, escribe /res confirm y el residence se borrar&aacute;.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Como cambio el mensaje de bienvenida y salida de mi residence?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Para cambiar el de entrada escribe:</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res message enter MENSAJE DE ENTRADA</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Para cambiar el de salida escribe:</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res message leave MENSAJE DE SALIDA</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Que mas comandos podemos usar?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res list: Este comando te dice los terrenos que t&uacute; tienes, simplemente te dice como se llama.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res info: Te dar&aacute; toda la informaci&oacute;n del terreno en el que te paras, as&iacute; como el nombre, el creador, el tama&ntilde;o, los permisos que tiene ese terreno y los permisos que t&uacute; tienes hacia ese terreno.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res ?: Este comando lo que hace es tar todas las opciones disponibles en el plugin.</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&iquest;Como le doy permisos a un usuario?</b><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Para darle permisos a usuarios usaremos el comando estando dentro de la res:</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">/res pset NOMBREJUGADOR +FLAG true o false</span><br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<br style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;" />
<b style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">Ej:</b><span style="color: rgb(4, 4, 4); font-family: 'Helvetica Neue Light', HelveticaNeue-Light, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 19.600000381469727px; text-align: justify;">&nbsp;/res pset juanita&nbsp;build t&nbsp;- As&iacute; me das permisos de construcci&oacute;n en tu residence. As&iacute; con todos los permisos que puse antes arriba.</span></p>


                <br />
